name: Build and Test

on:  
  push:
    branches: 
     - main
     - develop
     - 'feature/**'
  pull_request:
    branches: 
     - main
     - develop
     - 'feature/**'

jobs:  
  build-and-test:    
    runs-on: windows-2019
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore Encountify.sln

      - name: Build Solution
        run: |
          msbuild.exe Encountify.sln 
          
      - name: Test
        run: |
          cd AppTests
          cd bin
          cd Debug
          ls
          vstest.console AppTests.dll